### ISSUE TITLE
Icons are too far to the right

### ISSUE THREAD

**Issue by ericzx505** [akshat46/FlyingFox#11]
when using the configuration given the icon for the website barely show up on the right side. It maybe because I am using a smaller screened laptop or maybe because I am using GNU IceCat, but I'm not for sure
![issue](https://user-images.githubusercontent.com/51841858/82966398-4646cd00-9fba-11ea-8c94-008f752c8cc2.png)

**Comment by akshat46** [comment]
Just confirming, do you have "right side" selected under tree style preferences? 
![image](https://user-images.githubusercontent.com/7402043/82972197-48446800-9f89-11ea-84cd-512a048f13a6.png)

Also, did you change `initial-width` and `sidebar-width` in `vars.css` that you have under your chrome directory? If you didn't then the size of your screen shouldn't matter. UserChrome would have been impacted by the fact that you are using IceCat, which it isn't. This seems like a tst issue.

**Comment by ericzx505** [comment]
![rightside](https://user-images.githubusercontent.com/51841858/82981193-ea407080-9fda-11ea-9c93-502ede4837cb.png)
Also I have not changed anything in the vars.css file. it is the same as the one here on the github.

I also want to thank you for taking the time to try to help me out.

**Comment by akshat46** [comment]
That's weird. Not really sure how screen size would affect positioning. I have just pushed a small workaround. Can you copy the content of [treestyletab/custom.css](https://github.com/akshat46/FlyingFox/blob/master/treestyletab/custom.css) to your treestyletab's custom css? 
It's pretty much the same thing except the `favicon-shift` variable. Poke around with its value and it should fix both, the tab favicon and the close button that shows up when tab is hovered. Let me know if that works.

**Comment by ericzx505** [comment]
When I adjust the facicon-shift variable it only moves the close button when hoving over a tab. The icon itself stays slightly off to the right of the edge of the tab bar. If I leave the variable blank the icon will show and the close button will be pushed to the left.

**Comment by evansan** [comment]
Same issue, Windows 10, new profile, all default configs
![image](https://user-images.githubusercontent.com/2133205/83829358-a7ecf280-a6b0-11ea-91c8-cfe80ed6525e.png)

**Comment by evansan** [comment]
I left favicon-shift black instead of 0, fixes this problem.
