### ISSUE TITLE
Top tab bar still showing up, side tab bar not collapsing

### ISSUE THREAD

**Issue by deepakn97** [akshat46/FlyingFox#14]
Hey
Really nice work. .I am using Ubuntu 18.04 and I followed through all the steps and ended up with something like this. Along with the problems mentioned in the title(tried all the solutions provided by you), the UI doesn't quite look like yours
Also. I would like to know which dark mode theme you use in your setup. 
Sorry for any silly questions, new to firefox.

![Screenshot from 2020-07-23 12-10-25](https://user-images.githubusercontent.com/18685430/88258394-b84b4200-ccdd-11ea-913a-64d849adca16.png)

**Comment by deepakn97** [comment]
Was able to fix this behaviour. It was my bad. Now the icons in the sidebar sticking to the left side .

**Comment by UnchartedSystems** [comment]
What did you do to fix this issue?

**Comment by akshat46** [comment]
@UnchartedSystems Looks like deepak used `userChrome-static` instead of `userChrome-hover` at first. Adding [userChrome-hover](https://github.com/akshat46/FlyingFox/tree/master/chrome) correctly should fix it.
