### ISSUE TITLE
Style no longer works on new tree style tabs update

### ISSUE THREAD

**Issue by cinerea0** [akshat46/FlyingFox#15]
After updating to the newest version of tree style tabs, the tab style provided by this repo no longer works properly:
![tabs](https://user-images.githubusercontent.com/49368915/91370836-e81ac780-e7fe-11ea-9288-321e87a9562f.png)
I believe this might have something to do with the "vertigo" theme being deprecated. However, implementing [the recommended fix](https://github.com/piroor/treestyletab/wiki/Vertigo-theme-%28patch-for-the-theme-%22Plain%22%29) does not remedy the problem.

**Comment by danielrousseaug** [comment]
I'm having the same issue, would really appreciate a fix since im really in love with this style of firefox

**Comment by akshat46** [comment]
Should be fixed now. The css for tst is now based on the "Plain" tst theme.

**Comment by 291818147** [comment]
Very beautiful, but it doesn’t work on windows

**Comment by akshat46** [comment]
@291818147 It's still broken despite of getting new patches from this repo? What isn't working? A screenshot will help.

If it's not related to tst updates then please open a new issue with details about what isn't working.
