### ISSUE TITLE
MY icons dont seem to shift out on hover.

### ISSUE THREAD

**Issue by mxrixs** [akshat46/FlyingFox#17]
I just got the new version and changed everything to my liking (margins, colors, etc.) but the icons don't seem to go away when to closebox comes in [video](https://imgur.com/ephozZW) and [tst code](https://pastebin.com/uGLSp6Wu)

**Comment by akshat46** [comment]
Ah shoot. Thanks for pointing that out. One of the last commits seems to have messed up the TST custom css. I'll fix it in a bit. 
Meanwhile the most glaring mistake seems to be `ease-i-out` in `treestyletab/custom.css`. Replace it with `ease-in-out` and it _should_ work.

**Comment by akshat46** [comment]
Sorry about the aggressive closing. Keep forgetting  github closes the issue if it's mentioned with specific keywords in the commit message. Feel free to reopen it if you're still facing problems.
