### ISSUE TITLE
Close button styling, Background Colour, and Hover not working

### ISSUE THREAD

**Issue by EliotHertenstein** [akshat46/FlyingFox#19]
I'm having a few problems. 

Firstly, this may just be an overall thing, but there seems to be a square around the "close tab" button 
![image](https://user-images.githubusercontent.com/39346975/100771833-bb54ee00-33b3-11eb-889d-5f7033de657c.png)

Secondly, I'm having trouble getting my background to change, or the sidebar to collapse. I've attached my chrome folder below.
[chrome.zip](https://github.com/akshat46/FlyingFox/files/5624151/chrome.zip)

I appreciate any help!

Thanks for making such an awesome project. Hopefully, I can get it working soon :)

**Comment by akshat46** [comment]
Sorry about the super late reply. The box around close button might have been some change in tst update. I am a little busy these days but I'll try to look at it next week. 
As per the sidebar issue, the most glaring problem I see is your vars file is actually named `var.css` while it's supposed to be `vars.css`. If fixing that doesn't work then maybe move the userChrome-hover import in your userChrome after all the other imports in case something else is also styling sidebar.

**Comment by EliotHertenstein** [comment]
Hi! renaming vars.css seems to have fixed the sidebar collapsing! One new problem the menu toolbar seems to be always showing at the top of the screen, to the left of the nav buttons.
![image](https://user-images.githubusercontent.com/39346975/101084777-4fb18300-3563-11eb-9dc9-18553f4c88fb.png)
![image](https://user-images.githubusercontent.com/39346975/101084795-56d89100-3563-11eb-90cc-8d73c7844952.png)
Also, there are some spacing issues with the nav buttons on windows. 
![image](https://user-images.githubusercontent.com/39346975/101084839-6657da00-3563-11eb-8d81-c0a5ebb609f5.png)
 ![image](https://user-images.githubusercontent.com/39346975/101084856-6ce65180-3563-11eb-9868-cbfa4e6c182a.png)

Again these are minor aesthetic issues that I can probably fix myself, I just wanted to let you know. I really appreciate all the work that you've put into this project! Much love ❤

**Comment by akshat46** [comment]
I think the menu bar usually only pops up when you press alt. If you don't want it to show up at all you can set `ui.key.menuAccessKeyFocuses` to false in about:config and that should fix it. 

If you check title bar in Firefox customization, the controls should show up on a separate title bar.
