### ISSUE TITLE
weird navigation bar on mac

### ISSUE THREAD

**Issue by alzedd** [akshat46/FlyingFox#21]
![Schermata 2020-12-04 alle 12 15 37](https://user-images.githubusercontent.com/29459468/101157455-738bcc00-362a-11eb-9721-8d7135aebde0.png)

**Comment by sheeepdev** [comment]
@akshat46 please help i have that same too, I have just a dark thing on the left :(

**Comment by akshat46** [comment]
This should be fixed with the new release. Feel free to reopen.
