### ISSUE TITLE
change colors

### ISSUE THREAD

**Issue by pjhalsli** [akshat46/FlyingFox#28]
Hi - I've been trying to change colors - I want to use #1c2c2c or #212121 as background color but no matter what i do nothing changes. All my programs and terminals are either ¤1c1c1c or #212121 so for the consistent look 'i 'd like this to follow the same colors.  Any idea how I can achieve this?

edit:
Also want to thank you for this- I've used nighttab for over a year now - but this is just amazing so if I can change it so it fits with my other colors this will be my new go to.

edit 2
I tried to change sidebar bg color to 1c1c1c but after the restart, it showed the same color - no change

including a pic so you see what 
i  mean
https://imgur.com/a/Nu3Oo43

**Comment by akshat46** [comment]
Have you tried [firefox color](https://color.firefox.com/) yet? That was my primary means of changing color schemes and it should work, _at least for everything except sidebar._ 
In case it isn't able to change sidebar color, adding this CSS to TST should work: 
```CSS
:root, #background{
    background:  #212121;
}
```

**Comment by pjhalsli** [comment]
Yeah ff color wors fine but rhe sidebar wouldnt change. Will try rhe solution you posted when i get home. Thx in advance

**Comment by pjhalsli** [comment]
Worked perfectly - thank you
