### ISSUE TITLE
New store for FirefoxCSS themes

### ISSUE THREAD

**Issue by Neikon** [akshat46/FlyingFox#29]
Hi, I don't know how to contact you so I'm using this.

We are creating a website where to collect firefox themes. we have included yours by linking to this github. But we don't have a good preview image of your theme. It would be nice if you could provide it.

I invite you to add/change/remove any information we have added to our website. I hope you like the initiative and that in the future you will send us more themes.

here are the links:
web: https://firefoxcss-store.github.io/
repo: https://github.com/FirefoxCSS-Store/FirefoxCSS-Store.github.io

Regards :)

**Comment by akshat46** [comment]
Thanks a lot for including flyingfox! Looks like a great project. [img/normal.png](https://github.com/akshat46/FlyingFox/blob/master/img/normal.png) seems like a good preview image. I'll make a pull request with its url soon.
