### ISSUE TITLE
Little Problem with Linux Version

### ISSUE THREAD

**Issue by Rodrigo-Barros** [akshat46/FlyingFox#3]
Hi I seen your post on reddit, and I decide try it out ,but I did face an problem that not all fields was receive the correct color, and a piece was white clashing from overall, I dont know if I lost something on middle of process, or the addon was updated with something new, but anyway I made this little hack and everyhing is working great as in your post.

this rule on chrome.css not working for me

```
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"].... {
   display: none !important;
}
```

my little hack to fix my issue:

```
#sidebar-box{
  background: #31313a !important;
}
```
PS: Great Theme, Congratulations 👏👏👏 for your job.

**Comment by akshat46** [comment]
Thanks for the solution. I've added this to userChrome. Closing the issue now.
