### ISSUE TITLE
icon alignment for tree and active tab

### ISSUE THREAD

**Issue by benneti** [akshat46/FlyingFox#33]
As the title says, it would be nice to have all tab icons aligned the same, right now tree tabs as well as the active tab are too far right which looks slightly broken.
See screenshot for an example:
![Screenshot from 2021-02-07 15-17-09](https://user-images.githubusercontent.com/11725645/107149255-e03b8380-6957-11eb-9235-5849f8cc45df.png)

**Comment by akshat46** [comment]
This has been a problem with branching and hover for quite a while. I have just added [tst/config-hover.css](https://github.com/akshat46/FlyingFox/blob/master/treestyletab/custom-hover.css) which I think is handling branching with hover relatively well.Can you put it in your tst config and see if it works? 
_**Make sure you have "Left side" selected for sidebar position.**_  Contrary to the previous config, this one does not require "right side" sidebar position selected for hover.

**Comment by benneti** [comment]
yes thank you, loading the new config.json and new css it looks way better now!
