### ISSUE TITLE
Theme does not work on Windows if window-controls are included

### ISSUE THREAD

**Issue by akshat46** [akshat46/FlyingFox#35]
![image](https://user-images.githubusercontent.com/7402043/107194284-b3fa2400-69a4-11eb-9011-c93ee88f157d.png)

![image](https://user-images.githubusercontent.com/7402043/107194600-19e6ab80-69a5-11eb-893f-3cc5df471d77.png)

**Comment by sheeepdev** [comment]
please fix this

**Comment by sheeepdev** [comment]
nevermind I took the code from another firefox CSS for the window controls and works flawlessly

**Comment by InternetOscar** [comment]
which firefox css did you use?

**Comment by sheeepdev** [comment]
> 
> 
> which firefox css did you use?

https://www.deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916

**Comment by akshat46** [comment]
> > which firefox css did you use?
> 
> https://www.deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916 this one and I took the caption buttons part in the userChrome.css

Sweet! Thanks a lot for updating here. I hadn't touched my Windows laptop in years so its taking a bit of time to make it functional. I'll refer to that code and try to patch it soon.

**Comment by sheeepdev** [comment]
> 
> 
> > > which firefox css did you use?
> > 
> > 
> > [deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916](https://www.deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916) this one and I took the caption buttons part in the userChrome.css
> 
> Sweet! Thanks a lot for updating here. I hadn't touched my Windows laptop in years so its taking a bit of time to make it functional. I'll refer to that code and try to patch it soon.

Ill make a pull request

**Comment by sheeepdev** [comment]
> 
> 
> > > which firefox css did you use?
> > 
> > 
> > [deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916](https://www.deviantart.com/dpcdpc11/art/Nord-for-Firefox-837860916) this one and I took the caption buttons part in the userChrome.css
> 
> Sweet! Thanks a lot for updating here. I hadn't touched my Windows laptop in years so its taking a bit of time to make it functional. I'll refer to that code and try to patch it soon.

I'm getting in contact with the theme maker, I need to get permission to use this snippet of code the code is licensed by the [cc 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/)

**Comment by sheeepdev** [comment]
nice! Thanks for fixing this :)
