### ISSUE TITLE
Treestyletab static

### ISSUE THREAD

**Issue by Boxit379** [akshat46/FlyingFox#37]
Treestyletab static even though I use the hover css
![screenshot](https://user-images.githubusercontent.com/66697315/107315403-d5feaf80-6a53-11eb-80a7-52e71a69c24d.png)

**Comment by akshat46** [comment]
You're likely including both userChrome-hover and userChrome-static while static being the last one to be included. You could try selecting `hover` in [the app](https://flyingfox.netlify.app/generate) and replacing the `config.css` in your chrome folder with the one on there. 
I would be able to help more if you could paste your `config.css` and wherever else you tried to include userchrome-static.

**Comment by Boxit379** [comment]
> 
> 
> You're likely including both userChrome-hover and userChrome-static while static being the last one to be included. You could try selecting `hover` in [the app](https://flyingfox.netlify.app/generate) and replacing the `config.css` in your chrome folder with the one on there.
> I would be able to help more if you could paste your `config.css` and wherever else you tried to include userchrome-static.

Oh, thanks! Turns out I had both in the folder and was using the userChrome-hover as the css on the extension configuration.. It's working now :)
