### ISSUE TITLE
Hover sidebar

### ISSUE THREAD

**Issue by thomoeda** [akshat46/FlyingFox#41]
**Describe the bug**
I can't hover the sidebar...

**To Reproduce**
Try to hover and nothing hapens...

**Screenshots**
https://i.imgur.com/sMzwgAk.gif

 **Firefox Version:**
85

**Comment by thomoeda** [comment]
after retrying downloading the script from the website I could do it but its buggy...

https://i.imgur.com/pQYP75v.gif

**Comment by akshat46** [comment]
You seen to be using custom.css right now. You have to paste custom-hover.css in TST preferences for hover sidebar as stated in [the wiki](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#treestyletab-css).

**Comment by thomoeda** [comment]
> 
> 
> You seen to be using custom.css right now. You have to paste custom-hover.css in TST preferences for hover sidebar as stated in [the wiki](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#treestyletab-css).

hello, i'm not, as you can see in my gif: https://i.imgur.com/sMzwgAk.gif
I load custom-hover.css in tst preferences
After I load the custom-hover from the website (not that one in github) it's hovering but still with a bug as you can see here: https://i.imgur.com/2oTRM3Q.png
I tried different ways to fix it but can't

**Comment by akshat46** [comment]
Oh there is no custom-hover on the web app right now. I'll fix that in a bit. But in the first gif, there doesn't seem to be any userchrome-hover included. For hover to work flawlessly, you need two things: userchrome-hover included in your userChrome, and config-hover in your tst preferences. 

I see you've also changed theme. Once you have the above two stated things, you can copy just the colors bit of css (the :root{...colors} parts towards the top of tst css). I'll also fix the web app to show tst-hover css separately in a bit.

**Comment by thomoeda** [comment]
Well if you mean userchrome-hover in the userchrome folder, here it's: https://i.imgur.com/Z1hHFiy.png
and the config-hover is already in tst preferences
the problem here right now is only for the favicons bugged

**Comment by akshat46** [comment]
Yes, along with keeping `userchrome-hover` in your `chrome` folder, you'll have to include it in your `userChrome.css` or `config.css`. It will be included in your `config.css` if you get the one from web app after selecting "hover" from the sidebar menu.

No worries. I'm happy to help! Were you able to solve this? Feel free to reopen if you run in more problems.
