### ISSUE TITLE
Webapp outputs outdated variable names regarding Window Control placement

### ISSUE THREAD

**Issue by asla9709** [akshat46/FlyingFox#42]
**Describe the bug**
When generating a "config.css" from the webapp, it includes the variable `--wc-horizontal-shift`, when the actual variables in the config should be `--wc-left-space` and `--wc-right-space`. This has the effect of disabling the window controls when the generated config is used.

**To Reproduce**
1. Go to https://flyingfox.netlify.app
2. Click on "Customize"
3. Click on the "Settings" icon, and then the "Code" icon on the top right.
4. Generated config.css has the wrong variable.

**Screenshots**

 **Firefox Version:**
85.0.1

**Comment by akshat46** [comment]
Thanks for pointing this out. Deploy pipeline was pointing to an old branch. Fixed now.
