### ISSUE TITLE
Hover configuration not working

### ISSUE THREAD

**Issue by regan3** [akshat46/FlyingFox#43]
After following the installation instructions from the wiki everything looks ok except the sidebar seems to be static even though I used `custom-hover.css` when configuring TST. Strangely enough, the bookmarks bar is now hidden and unhidden upon mouse hover but not the sidebar. Any ideas?

 Mozilla Firefox for Arch Linux Version 85.0.2

**Comment by akshat46** [comment]
Along with custom-hover for TST, you'll also need userChrome-hover included in your config.css. Can you check if that's setup properly in your chrome folder? 
Easiest way to do this would be getting the config.css through the webapp since it removes incorrect files, and includes correct ones based on options. For e.g if this were to be done manually, importing userChrome-static anywhere after userchrome-hover would overwrite hover rules and revert to a static sidebar since CSS is compiled chronologically.

**Comment by regan3** [comment]
Yeah I didn't have `userChrom-hover.css` included in my `config-css`. I had not used the web app for configuration yet because I though it was only for color. The sidebar hover works fine now although I have encountered another minor bug where there is still space for the tabline at the top of the window even though it is empty with `hide-tabline.css` included. All that shows in that top space is the the arrow button that shows the open tabs in a dropdown. If I include `window-controls/wc-without-tabline.css` there's no more empty space, but I would rather not have the other effects of `window-controls/wc-without-tabline.css`. Any idea how I can get rid of the extra space?

**Comment by akshat46** [comment]
The main purpose for `wc-without-tabline` was to handle tablines, not including it was supposed to just leave the window controls alone to be handled by your own CSS. If you don't want the entire window controls(and empty space) don't include `wc-without-tabline` instead add this to `userChrome`: 

```CSS
#TabsToolbar{
    display: none !important;
}
```

**Comment by regan3** [comment]
Great thanks for your help! My last question is about reducing the padding on the navbar. I'm fine with the icon sizes and all that but would like to be able to "squeeze" everything vertically by reducing the padding above and below the urlbar and buttons. Unfortunately I know nothing about CSS and can't make much sense of `navbar.css` beyond trial and error.

**Comment by akshat46** [comment]
Changing [this](https://github.com/akshat46/FlyingFox/blob/master/chrome/navbar/navbar.css#L14) `padding` value should do the trick. Along with top and bottom, this line also controls the left and right padding of the navbar. If you want different top-bottom and left-right padding, set it to something like `4px 8px` where 4px will be the top-bottom padding and 8px would be for left-right.

**Comment by regan3** [comment]
Perfect thanks for the help and the awesome config! Earned a star from me for sure.
