### ISSUE TITLE
Right handed Window Control

### ISSUE THREAD

**Issue by RobertNelsonMSUDenver** [akshat46/FlyingFox#44]
On windows, switching between using left handed controls for firefox and right for literally every other program renders inline window controls virtually useless. It would be nice if there was a possibility to align window controls with the rest on the OS on Windows and Linux with a control of where its placed.

**Comment by Frai7ty** [comment]
Make the following changes in the following files. Sorry if there is a better way to post this, new to github (Or this in general)

config.css
 
  --wc-vertical-shift: 18px;
  --wc-left-space: 10px; /* add space to the left of window controls*/
  --wc-right-space: 16px; /* add space to the right of window controls*/

wc-without-tabline.css

#TabsToolbar.browser-toolbar {
    display: inline-block !important;
    position: absolute;
    top: var(--wc-vertical-shift) !important;
    right: var(--wc-left-space) !important;


}

window-controls.css
:root:not([inFullscreen]) toolbar#nav-bar {
    z-index: 1 !important;
    position: relative !important;
    margin-right: calc(
        var(--wc-right-space) * 2 + 60px
    ) !important; /* shift toolbar to the right based on initial width */
}

**Comment by akshat46** [comment]
Thanks @Frai7ty. This has been added as an [optional file](https://github.com/akshat46/FlyingFox/blob/dev/chrome/window-controls/wc-without-tabline-r.css). Will include it with the next release.
