### ISSUE TITLE
Broken with the latest Firefox and TreeStyleTab Update 

### ISSUE THREAD

**Issue by piyush-das** [akshat46/FlyingFox#45]
Hi,

After updating firefox and the TreeStyleTab to the latest version. The complete CSS seems to be broken, I have tried reinstalling following the `wiki` however, it just doesnt seem to work out. 

Issues:
1. As soon as the chrome and user.js files (downloaded from the releases) are pasted in the profile directory.  the UI messes up.
2. Even after loading the custom-hover.css , the sidebar remains static.

**Screenshots**
![Screenshot from 2021-02-21 08-59-13](https://user-images.githubusercontent.com/68941107/108614762-7923d180-7423-11eb-88b6-5cd04d9c789a.png)

 Firefox Version: 85.0.1

Please let me know if I am missing something.

Thanks

**Comment by akshat46** [comment]
I can't get on my setup right now but will test in a bit. Meanwhile can you confirm if you're using dark or light theme under customize? 

Last time I checked latest Firefox I remember seeing a few new themes. If I remember correctly the default theme were separate from the traditional dark and light ones.

**Comment by piyush-das** [comment]
I was on the default there. Here's the differences.

Dark Theme
![Screenshot from 2021-02-21 09-38-48](https://user-images.githubusercontent.com/68941107/108615280-a3c45900-7428-11eb-82cb-775a8296e0fa.png)

Light Theme
![Screenshot from 2021-02-21 09-39-42](https://user-images.githubusercontent.com/68941107/108615299-c22a5480-7428-11eb-801f-38b3d196bc80.png)

Default Theme
![Screenshot from 2021-02-21 09-40-43](https://user-images.githubusercontent.com/68941107/108615325-e25a1380-7428-11eb-88c3-a4d148bfc276.png)

Seems like switching to the dark theme is the way to go. However the problem with the non hovering of the sidebar still persists.

**Comment by akshat46** [comment]
For hover sidebar to work, along with custom-hover for TST css you'll also need to make sure userChrome-hover is included in your chrome folder. [Take a look at this.](https://github.com/akshat46/FlyingFox/issues/43#issuecomment-781880002)

**Comment by piyush-das** [comment]
@akshat46 Works as expected now. Perhaps this could be added to the installationg `wiki` notes when we are installing form the releases insteaf of the webapp, which includes the userChrome-hover by default when Hovering is enabled.

Thanks.
