### ISSUE TITLE
Sidebar not collapsing with the TST custom-hover.css

### ISSUE THREAD

**Issue by Griffinhart** [akshat46/FlyingFox#46]
FlyingFox 0.1.1, Firefox 86.0, Windows 10.

Sidebar remains open/uncollapsed even when mouse is nowhere near it. I can still toggle the sidebar on/off via hotkey (`F1`). When I mouseover a tab in the sidebar, the "close tab" icon pops unhides.

Bookmarks toolbar collapses/autohides.

**Comment by aashu** [comment]
see discussion at #43 , Import userChrome-hover.css in config.css to fix this.

**Comment by Griffinhart** [comment]
That fixed it. Thanks.
