### ISSUE TITLE
TST hover is not working

### ISSUE THREAD

**Issue by green-stalk** [akshat46/FlyingFox#47]
Everything else in the tabs works exactly as in the video, but when the cursor is removed the tabs do not hide. I imagine this is probably me doing something wrong in the install process since I'm fairly new to all this. I followed the instructions in the wiki to get to this point, and I have looked further into the readme files, but they just don't make any sense. I still have config.json unused, but the readme file says I need to use the import button in the extension options, but no such button exists. Please help?

This is with Firefox 86.0 btw

**Comment by akshat46** [comment]
I'm assuming you've also setup userChrome properly? The first step under installation doc. 

Take a look at [#43](https://github.com/akshat46/FlyingFox/issues/43#issuecomment-781880002). The import statements are actually lines of code that you should/shouldnt be adding to config.css( which is in the chrome folder). If you're unfamiliar with CSS it might be easiest to go to flyingfox.netlify.app and switch to configuration, make sure "hover" is selected under sidebar, and download the config.css given their. Replace config.css in your chrome folder with the one installed.

**Comment by green-stalk** [comment]
Problem solved :) thanks for the help and sorry for being an idiot

**Comment by green-stalk** [comment]
![2021-02-25 (1)](https://user-images.githubusercontent.com/78030060/109191228-dc986100-778d-11eb-89d3-d05848ad86ae.png)

OK now I've replaced the config.css files, and I'm having the issue you can hopefully see where the default close and minimize etc buttons are still there, leading to a lot of blank space along the top

**Comment by green-stalk** [comment]
nvm, problem fixed. The issue was that the file given by flyingfox.netlify.app was missing`@import "window-controls/wc-without-tabline.css";`, so I just replaced that and it worked as normal again.
