### ISSUE TITLE
Unaligned icons

### ISSUE THREAD

**Issue by odelucca** [akshat46/FlyingFox#5]
Hey guys,

Fantastic work with this config =). I love it.

There is just a minor issue that I would like to solve. The icons from my toolbar are not aligned. Here is a screenshot:
![Screenshot](https://i.imgur.com/Mxy2Kds.png)

How can we fix this?

**Comment by akshat46** [comment]
Did you import the settings from `treestyletab/config.json`?  Looks like it might be an issue with style of content setting under tree style tab preferences but the first icon seems to be aligned. 
Something unrelated I am noticing, you have the tab row and minimize/close buttons. You can remove that entire row by ensuring you have "title bar" selected on the customize toolbar page.

**Comment by odelucca** [comment]
I've imported them. I think I forgot to restart Firefox, now that I've rebooted my computer it is aligned (with just the selected item a little to the right, but I think this is the desired behavior.

Closing the issue =)

Thanks.
