### ISSUE TITLE
[Request] Option to make tab favicons full color / not washed out

### ISSUE THREAD

**Issue by Bandit** [akshat46/FlyingFox#50]
Find it a bit difficult to tell between certain icons at a glance with them so washed out. Couldn't immediately see where to adjust this myself in the CSS

![image](https://user-images.githubusercontent.com/30508/110541931-4ac92480-818d-11eb-85f7-f4fe4c200f7f.png)

**Comment by akshat46** [comment]
The icon masks are set with the var extension-icon-mask near the top of tst css. Commenting it out should remove the style.

**Comment by Bandit** [comment]
Worked perfectly, thanks!

**Comment by akshat46** [comment]
Setting icon mask in this rule _should_ include all these browser specific favicons. 

```css
.tab .favicon .favicon-default::before {
    filter: grayscale(85%) invert(75%);
}
```

[Its already included in the tst css](https://github.com/akshat46/FlyingFox/blob/master/treestyletab/custom-hover.css#L209) but rendered useless once mask variable is removed. You can replace the `var(---extension-icon-mask)` with a correct mask value here.

**Comment by MrUltimate** [comment]
> ```css
> .tab .favicon .favicon-default::before {
>     filter: grayscale(85%) invert(75%);
> }
> ```

Perfect, that did it! Thanks.
