### ISSUE TITLE
FirefoxCSS: Window Controls Not Visible

### ISSUE THREAD

**Issue by weiameili** [akshat46/FlyingFox#51]
Hi, The buttons for the window controls are not visible

I did try different values for `wc-left-space`, `wc-right-space` and `wc-vertical-shift`, but everything was still the same (except for` wc-right-shift`)

I am using Deepin Linux Based on Debian Buster with the default DE, and my Firefox version is 86.0.1 (archive installed from their website)

**Comment by akshat46** [comment]
Not sure what the problem could be. Just tested on 86.01 and it seems to be working for me. 
![image](https://user-images.githubusercontent.com/7402043/111926907-f581f280-8a6b-11eb-8168-4623de1e22e8.png)
