### ISSUE TITLE
FirefoxCSS: Remove System Window Decorations

### ISSUE THREAD

**Issue by weiameili** [akshat46/FlyingFox#52]
Hi, on Deepin 20 (Debian Buster based) firefox uses the system titlebar, which does not go with the theme. I doubt this is a system issue because there are alot of apps that do not use the system titlebar (including edge annd chrome)

**Comment by akshat46** [comment]
Can you confirm that the "title bar" option under customize options in Firefox is not selected? That should remove title and, also fix the other issue regarding window controls not being visible.

**Comment by akshat46** [comment]
Removing both the issues for now. Feel free to open them again if your problem isnt fixed.
