### ISSUE TITLE
[IDEA] TST - Pin Tabs show up in sidebar

### ISSUE THREAD

**Issue by Frai7ty** [akshat46/FlyingFox#53]
Idea: Have Pin tabs show up without hover in TST.  Have them be top and protected, and at the beginning of the list. making them more similar to stock Firefox behavior.

Currently they sit up top and require more work than standard tabs to access. If they stayed in view as protected tabs it would improve their functionality. 

I'm don't currently know if this is CSS addressable or hard coded into TST.

**Comment by prediscover** [comment]
I had this working in TST but I lost my config! It is possible within TST, i Think.

**Comment by Frai7ty** [comment]
Found the setting in TST. Under appearance there is a setting "Show pinned tabs only with their icon" you can uncheck. It is now working as I suggested.

**Comment by Frai7ty** [comment]
![image](https://user-images.githubusercontent.com/3834210/111410231-bee45a80-86ae-11eb-86ba-26213aa57ca2.png)
