### ISSUE TITLE
Website favicon colors reset to default

### ISSUE THREAD

**Issue by sheeepdev** [akshat46/FlyingFox#57]
![2021-03-27-183036_199x41_scrot](https://user-images.githubusercontent.com/68562536/112729090-b6034c80-8f2a-11eb-8839-b70277f6fd29.png)

When i hover over it (im focused on the icon with the mouse) it's normal

But if i dont the icon resets to default
![2021-03-27-183022_50x47_scrot](https://user-images.githubusercontent.com/68562536/112729113-ce736700-8f2a-11eb-9fae-551d7ee95aba.png)

If you need info, im running firefox 87.0 on arch linux.

**Comment by akshat46** [comment]
I can't recreate this on my end with v0.1.2. Can you post your TST CSS? Seems like the icon-mask rule might be getting overridden.

**Comment by sheeepdev** [comment]
> I can't recreate this on my end with v0.1.2. Can you post your TST CSS? Seems like the icon-mask rule might be getting overridden.
> 
> Edit: Actually I just noticed, I think you are using old TST css. With v0.1.1 Flyingfox started including a `custom-hover.css` which styles the "Left side" set sidebar for hover, instead of styling everything with `custom.css` and requiring "Right Side" chosen in TST settings. You can find details [in the wiki](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#treestyletab-css).

seems that that did it, ty!
