### ISSUE TITLE
[Request] blur in URL Bar

### ISSUE THREAD

**Issue by f4t7** [akshat46/FlyingFox#58]
**Not a Bug just a simple request**
Is there a way you can add blur effect behind the url bar?

**Comment by f4t7** [comment]
Also in the tree style tab if possible

**Comment by akshat46** [comment]
There's a few blur based themes out there for firefox but I think adding blur to flyingfox will make it difficult to maintain and my schedule has been stretched thin lately as is so don't have any plans to add blur of any kind. Sorry. Closing the issue.
