### ISSUE TITLE
Large gap between top of window and URL bar

### ISSUE THREAD

**Issue by cinerea0** [akshat46/FlyingFox#59]
**Describe the bug**
Using this configuration, there is a large gap between the top of the Firefox window and the URL bar.

**To Reproduce**
1. Install FlyingFox with hide-tabline and userChrome-hover.

**Screenshots**
![flyingfox](https://user-images.githubusercontent.com/49368915/112741830-73686100-8f78-11eb-9b95-0286f5f44969.png)

 **Firefox Version:** 87.0

**Comment by cinerea0** [comment]
Also, I'd be interested in knowing how to disable the bookmark bar that comes up on hovering on the URL bar on new tabs.

**Comment by akshat46** [comment]
That's weird. Somehow I never noticed that. Thanks for bringing it up! You can fix it by adding the following CSS to `userChrome.css`. 

```css
#titlebar{
    display: none;
}
```

Will include this in next release.

> Also, I'd be interested in knowing how to disable the bookmark bar that comes up on hovering on the URL bar on new tabs.

If you want to disable "show on hover behavior" of bookmark toolbar, you can do it as shown in https://github.com/akshat46/FlyingFox/issues/36#issuecomment-775125728. If you want to turn off the bookmark toolbar altogether you can disable it by: right click anywhere on navbar > deselect bookmark toolbar.

**Comment by cinerea0** [comment]
Adding that snippet fixed the issue, thank you! As for the bookmark bar, I wanted to disable it entirely and didn't know about the right-clicking trick. Thanks for everything and the work you put into this project; closing this now.
