### ISSUE TITLE
White space between navbar and sidebar

### ISSUE THREAD

**Issue by odelucca** [akshat46/FlyingFox#6]
Hey guys =)

Just another issue I notice, right above the sidebar there is an white block:

![Screenshot](https://i.imgur.com/fGpyWbU.png)

How can I fix it?

**Comment by akshat46** [comment]
Few others have mentioned this as well but I can't seem to recreate it. Can you try changing menubar height to `--menubar-height : -0px;` in `userChrome.css`? You will have to restart firefox after it. 
Also just confirming, do you have any of the toolbars selected on "customize toolbar" page?

**Comment by odelucca** [comment]
@akshat46, changing the `--menubar-height` at line 16 solved the issue =)

Thanks!

I'm closing it
