### ISSUE TITLE
Align Window Controls with other icons

### ISSUE THREAD

**Issue by hbarsaiyan** [akshat46/FlyingFox#62]
**Describe the bug**
The window controls are not aligned with other icons on toolbar.
![Screenshot from 2021-04-12 13-10-16](https://user-images.githubusercontent.com/37732050/114359952-04882c00-9b64-11eb-8113-66dff3fca439.png)

wc-without-tabline-r.css:
```
@import "window-controls.css";
@import "wc-without-tabline.css";

#TabsToolbar.browser-toolbar {
    left: auto !important;
    right: var(--wc-right-space) !important;
}

:root:not([inFullscreen]) toolbar#nav-bar {
    margin-left: 0 !important;
    margin-right: calc(var(--wc-left-space) * 2 + 72px) !important;
}

.titlebar-buttonbox {
    flex-direction: row !important;
}
```

**OS:** Arch Linux
 **Firefox Version:** 87.0

**Comment by akshat46** [comment]
You should be able to control vertical positioning of window-controls with the variable ` --wc-vertical-shift` in `config.css` as shown [here](https://github.com/akshat46/FlyingFox/wiki/5.-Window-Controls). Does that work?

**Comment by hbarsaiyan** [comment]
Yes thank you that solved it. Should have done the reading before.
