### ISSUE TITLE
Firefox 87: Sidebar not showing

### ISSUE THREAD

**Issue by hexa-one** [akshat46/FlyingFox#63]
**Describe the bug**
No sidebar or tabs are shown.

**To Reproduce**
/

**Screenshots**
![image](https://user-images.githubusercontent.com/58103738/114389410-3f568800-9b95-11eb-9713-b74a2fcfcb12.png)

 **Firefox Version:87**

**Comment by akshat46** [comment]
Do you have [TreeStyleTab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) Installed? If you do, you'll also have to toggle it. Default shortcut for toggling is `F1`.

**Comment by hexa-one** [comment]
> Do you have [TreeStyleTab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) Installed? If you do, you'll also have to toggle it. Default shortcut for toggling is `F1`.

That was indeed the problem.

**Comment by iamalmiir** [comment]
But then it's not styled with theme, can I change that?
