### ISSUE TITLE
How to hide the address bar and show it on hover only

### ISSUE THREAD

**Issue by modkavartini** [akshat46/FlyingFox#64]
you saw the title, it's basically working the opposite way of how its supposed to. i tried everything in #43 but its not working, pls help

**Comment by akshat46** [comment]
Do you have any of your own css? That might be overriding stuff. If not then it's either a problem with import statements, or config variables. Can you show contents of your `userChrome.css` and `config.css` files?

**Comment by ModkaVartini** [comment]
Sorry, this was my first time using a firefox theme and I'm dumb
My sidebar was set to right side, thats why it was acting the way it wasn't supposed to.
My apologies for wasting your time, but now that you're here, could I know if I can make my address bar show the url or itself on hover only? I'm pretty bad at css.
Thanks!
