### ISSUE TITLE
Style won't apply to Tree style tab and new tab

### ISSUE THREAD

**Issue by iamalmiir** [akshat46/FlyingFox#67]
I really don't know how to fix this,

Thanks in advance.

<img width="277" alt="Screen Shot 2021-04-17 at 5 20 43 AM" src="https://user-images.githubusercontent.com/78283120/115108116-b21c8600-9f3c-11eb-9db0-b98885e3e8de.png">
<img width="1440" alt="Screen Shot 2021-04-17 at 5 21 21 AM" src="https://user-images.githubusercontent.com/78283120/115108132-c6608300-9f3c-11eb-8199-2c137b15fcbb.png">

**Comment by akshat46** [comment]
You have to paste the content of `treestyletab/custom.css` for static sidebar, or `treestyletab/custom-hover.css` for hover sidebar in tst configs as shown in the last 2 steps of [tst installation](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#treestyletab-css).

**Comment by iamalmiir** [comment]
Fixed. Thanks a lot!

**Comment by iamalmiir** [comment]
Only new tab still looks the same. I was reading through the closed issues but nothing so far.

**Comment by akshat46** [comment]
As shown [here](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#options) you'll have to make sure `userChrome-hover.css` is included in your `config.css` and userChrome-static.css` is not included. 

> ```diff
> + @import "userChrome-hover.css";
> - @import "userChrome-static.css";
> ```

**Comment by iamalmiir** [comment]
It really worked I was blind. Thanks a lot for being passionate with me.

Can I display icons here instead of text or no?

![image](https://user-images.githubusercontent.com/78283120/115125003-76f97180-9f93-11eb-8e98-a7c293722589.jpeg)

Thank you once again!

**Comment by akshat46** [comment]
No problem.

Pasting `treestyletab/custom-hover.css` in treestyletab configs as I mentioned earlier will make the icons right aligned. 

> You have to paste the content of `treestyletab/custom.css` for static sidebar, or **`treestyletab/custom-hover.css` for hover sidebar** in tst configs as shown in the last 2 steps of [tst installation](https://github.com/akshat46/FlyingFox/wiki/%23-Installation#treestyletab-css).

On a side note, your window-controls look misaligned with rest of the navbar. You can fix that by tinkering with the `--wc-vertical-shift` variable in `config.css` as explained [here](https://github.com/akshat46/FlyingFox/wiki/5.-Window-Controls).

**Comment by iamalmiir** [comment]
Wow great man! I don't even know what to tell you. Thanks!!!🙌🏻🙌🏻
