### ISSUE TITLE
Changing tabline/bookmark bar height

### ISSUE THREAD

**Issue by 6ftClaud** [akshat46/FlyingFox#68]
The tabline, urlbar and bookmark bar together make up to a pretty hefty size.
Are there any values I can edit to change their height and make them a bit smaller?

**Comment by akshat46** [comment]
Unfortunately there aren't any variables in config file that can control heights. It was on my to-do list but my schedule won't allow expanding the scope of this project for a while. You can tweak these yourselves and see if it works: 

#navbar in [navbar/navbar.css](https://github.com/akshat46/FlyingFox/blob/master/chrome/navbar/navbar.css)(line #8). You can mess around with height, padding-inlinr,and padding properties which would change navbar height. Urlbar's values depend on these so you might have to tweak those too [here](https://github.com/akshat46/FlyingFox/blob/master/chrome/urlbar/urlbar.css)(line #132-#167 most of the height and padding properties). 

Change margin(line #2) in [userchrome-tabline](https://github.com/akshat46/FlyingFox/blob/master/chrome/userChrome-tabline.css) to change gaps in and around tabline.

**Comment by 6ftClaud** [comment]
Thank you for the quick reply! :)
Yeah, playing around with those did help.
I also found that in [variables.css](https://github.com/akshat46/FlyingFox/blob/master/chrome/variables.css) you can edit this to change tabs size  
https://github.com/akshat46/FlyingFox/blob/8fc00aa654c10260deac2cbbc5bf062b7dcce811/chrome/variables.css#L169  
  
Unfortunately I can't seem to be able to find how to edit the bookmark bar size :/
