### ISSUE TITLE
 [Feature Request] Hide the sidebar when fullscreen (F11)

### ISSUE THREAD

**Issue by Sky-NiniKo** [akshat46/FlyingFox#74]
Everything is said in the title

# Current behavior
![Current behavior](https://user-images.githubusercontent.com/61370893/118392663-70d7dd00-b686-11eb-9955-9e5144325162.png)

**Comment by akshat46** [comment]
With CSS the TST sidebar would be gone completely and won't be useable in full screen which is probably not the intention. I suggest you should set a shortcut to toggle the TST sidebar easily. You can do that by going to extensions page ( `ctrl + shift + a`) > cog wheel > manage shortcuts > scroll down to TST > set the "toggle tst sidebar" shortcut. Use that whenever you want to toggle hide tst sidebar. 

![image](https://user-images.githubusercontent.com/7402043/118414937-538e1900-b65c-11eb-912c-01b484637d0b.png)
