### ISSUE TITLE
Cut off minimise button

### ISSUE THREAD

**Issue by szarik010** [akshat46/FlyingFox#77]
**Describe the bug**
Half of the minimise button is cut off

**To Reproduce**
Install FlyingFox

**Screenshots**
![image](https://user-images.githubusercontent.com/84450794/119023480-de8f4c00-b999-11eb-9ed2-39741ea0cdbb.png)

 **Firefox Version:**
88.01

**Other Info**
Archlinux with Gnome

**Comment by akshat46** [comment]
Can you try increasing value of the variable `--wc-right-space` in config.css by a few pixels? You can find more detail about what exactly it does [here](https://github.com/akshat46/FlyingFox/wiki/5.-Window-Controls).

**Comment by szarik010** [comment]
Thanks. That fixed my issues
