### ISSUE TITLE
Tree Style Tab has a default style on Windows

### ISSUE THREAD

**Issue by JasperDre** [akshat46/FlyingFox#8]
Hi, thanks a lot for providing your instructions and configs.

I do have a question, because it looks like Tree Style Tab doesn't have the expected look and behavior. Even with the custom css and config in json it still acts as a static panel, unlike the one shown in the examples. Is this a known issue?

![image](https://user-images.githubusercontent.com/6676026/82697234-cdb5d880-9c68-11ea-8539-6911eb29ab77.png)

**Comment by akshat46** [comment]
Have you applied `userChrome.css` as well? None of its changes seem to have been applied in that screenshot. After doing that you'll have to restart firefox completely for it's effects to show up.

**Comment by JasperDre** [comment]
You're right, I had to move `userChrome.css` to a new folder called `chrome` within my profile folder for it to work. Cheers!

**Comment by akshat46** [comment]
Great. Closing the issue then.

**Comment by zaobas** [comment]
I seem to be having this same issue, except I've already moved the files to that directory. Tried restarting/resetting Firefox, but the changes still won't take effect. Also have legacy stylesheets enabled.

**Comment by akshat46** [comment]
@zaobas Does your firefox look exactly like the screenshot in this issue? If userChrome is not taking effect at all then it's most likely problem with `userChrome.css` placement. Also I have updated since yesterday so you'll also need to copy `vars.css` to your `chrome` directory as well.

**Comment by zaobas** [comment]
Yeah, it looks exactly like that; none of the changes take effect. I've tried moving both userChrome.css and vars.css to a new chrome folder within the profile folder itself, to the native chrome folder, within storage, and even within the AppData/Local profile. I've made sure the profile in the screenshot is my active profile.

![image](https://user-images.githubusercontent.com/46743420/82977588-4b9f1a00-9fb0-11ea-924c-8e7c0c8aef5c.png)

**Comment by akshat46** [comment]
OH you'll have to remove `-hover` from that file's name so rename it to `userChrome.css`. I put the `-*` extensions to make it easy to differentiate between all the variations of the sidebar. Restart firefox after renaming and it should work.

**Comment by zaobas** [comment]
Ah! That worked. Thanks for the help.
